request to merge Game branch with development branch
mohamednaser/Tic-Tac-Toe pull request #1
Opened 2020-04-27 15:13 UTC by mohamednaser

we finished below tasks : 
1- form to get players names 
2- design the game 
3- build winner logic 
4- build helper buttons to finish the game or restart it

2020-04-27 18:20 UTC, azdrenymeri requested changes
### Hello @mohamednaser  :wave: 
- [x]  `.git-ignore` file should be set to `.gitignore`(without the dash) so `Git` can recognize it.
Because of this typo all your project's `node_modules` are published on the remote branch so make sure to fix this.
- [x] Also stickler is not working(I'm guessing after fixing the `.gitignore` issue it will work), kindly check it out.
- [x] I can start the game without providing the player's name, let's add some validation on the form.
- [x] I see you have used Unobtrusive JavaScript on buttons in `index.html` kindly separate javascript from HTML.
#### Implement the changes and add it for another review

2020-04-27 18:20 UTC, azdrenymeri commented on index.html
> +            onclick="game.start()"
It is not a good practice to mix javascript with HTML.
You have already added the id, so on your js file
```javascript
document.querySelector('#start-game').addEventListener('click', () => {
game.start();
});
```

2020-04-27 18:20 UTC, azdrenymeri commented on index.html
> +                onclick="game.restart();"
Same as line 36.

2020-04-27 18:20 UTC, azdrenymeri commented on index.html
> +                onclick="board.reset()"
Same as line 36

2020-04-27 18:20 UTC, azdrenymeri commented on js/custom.js
> +// Global Tic-tak-toe Variables
Kindly remove all the comments on the file.

2020-04-27 18:20 UTC, azdrenymeri commented on js/custom.js
> +      console.log(selectedCell.id, "selectedCell details ", boardArray);
Remove the `console.log()` statements

2020-04-27 18:20 UTC, azdrenymeri commented on js/custom.js
> +    console.log("players data ", playerX, playerO);
Remove the `console.log()` statement.

2020-04-28 10:20 UTC, mcrd25 approved these changes
# Changes Approved 💪 🎉 🚀 

Hey @mohamednaser 👋 

Good job implementing changes requested from the previous review!
There is no need for further review now! 
Congratulations! ㊗️ 

Also, your game UI is very minimal and neat, I like it! 😄 

🚀 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-04-28 12:50 UTC, merged